name: AIBTemplate

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - ".github/workflows/aib.yml"
      - "workflow-artifacts/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "terraform"
  aib:
    name: "Azure Image Builder"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The environment will be used to determine which GitHub Secrets to use
    environment: production

    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/azure-login
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      # - name: Wworkspace contents
      #   run: ls ${{ GITHUB.WORKSPACE }}

      # https://github.com/marketplace/actions/build-azure-virtual-machine-image
      - name: Build custom VM image
        uses: azure/build-vm-image@v0
        with:
          resource-group-name: ${{ steps.terraform-apply.outputs.TF_RESOURCE_GROUP_NAME }}
          managed-identity: ${{ steps.terraform-apply.outputs.TF_MANAGED_IDENTITY_NAME }} # if the managed identity is in your resource group, you can simply reference it by name; otherwise you'll need to include the id of the object
          location: ${{ steps.terraform-apply.outputs.TF_LOCATION }}
          source-os-type: "Windows"
          source-image-type: "PlatformImage"
          source-image: microsoftwindowsdesktop:office-365:20h2-evd-o365pp:latest
          dist-type: "SharedImageGallery"
          dist-resource-id: ${{ steps.terraform-apply.outputs.TF_SHARED_IMAGE_ID }}
          dist-location: "westus2"
          customizer-script: |
            & 'c:\workflow-artifacts\say-hello.ps1'
          customizer-windows-update: true
          vm-size: "Standard_DS4_v2"
