name: Azure Image Builder

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 11 * */1 2"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_NAME: "rg-merrybison"
  AZURE_RESOURCE_GROUP_LOCATION: "westeurope"
  AZURE_MANAGED_IDENTITY_NAME: "msi-merrybison"
  AZURE_SHARED_IMAGE_GALLERY_NAME: "sigmerrybison"
  AZURE_SHARED_IMAGE_DEFINITION_NAME: "avd-merrybison"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "terraform"
  azure-image-builder:
    name: "Azure Image Builder"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The environment will be used to determine which GitHub Secrets to use
    environment: production

    defaults:
      run:
        shell: bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/azure-login
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      # - name: Wworkspace contents
      #   run: ls ${{ GITHUB.WORKSPACE }}

      # https://github.com/marketplace/actions/build-azure-virtual-machine-image
      - name: Build custom VM image
        uses: azure/build-vm-image@v0
        with:
          resource-group-name: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          managed-identity: ${{ env.AZURE_MANAGED_IDENTITY_NAME }} # if the managed identity is in your resource group, you can simply reference it by name; otherwise you'll need to include the id of the object
          location: ${{ env.AZURE_RESOURCE_GROUP_LOCATION }}
          source-os-type: "Windows"
          source-image-type: "PlatformImage"
          source-image: microsoftwindowsdesktop:office-365:20h2-evd-o365pp:latest
          dist-type: "SharedImageGallery"
          dist-resource-id: "/subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RESOURCE_GROUP_NAME }}/providers/Microsoft.Compute/galleries/${{ env.AZURE_SHARED_IMAGE_GALLERY_NAME }}/images/${{ env.AZURE_SHARED_IMAGE_DEFINITION_NAME }}"
          dist-location: "westeurope"
          customizer-script: |
            & 'c:\workflow-artifacts\say-hello.ps1'
          customizer-windows-update: true
          vm-size: "Standard_DS4_v2"
