name: FunctionDeploy

on:
  push:
    paths:
      - ".github/workflows/func.yml"
      - "functions/**"

env:
  AZURE_FUNCTIONAPP_NAME: func-ethicalbedbug # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./functions" # set this to the path to your web app project, defaults to the repository root

jobs:
  func-deploy:
    runs-on: windows-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
